"""user_id_in_tasks

Revision ID: 5835183bfce8
Revises: a17761a6b4ab
Create Date: 2025-03-23 15:20:25.779959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5835183bfce8'
down_revision: Union[str, None] = 'a17761a6b4ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Task', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Task', 'UserProfile', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Task', type_='foreignkey')
    op.drop_column('Task', 'user_id')
    # ### end Alembic commands ###
